variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_a_cidr" {}
variable "public_subnet_b_cidr" {}
variable "private_subnet_a_cidr" {}
variable "private_subnet_b_cidr" {}
variable "ami" {}
variable "instance_type" {}
variable "web_vm_attribute" {}
variable "pri_vm_attribute" {}